name = "mathrecord"
version = "0.1.0"
defaultTargets = ["Mathrecord", "gate0", "mathrecord"]

[[lean_lib]]
name = "Mathrecord"

[[lean_exe]]
name = "gate0"
root = "Mathrecord.Gate0"
supportInterpreter = true

[[lean_exe]]
name = "mathrecord"
root = "Mathrecord.Main"
supportInterpreter = true
